version: '3.1'

services:

  postgres:
    image: postgres:13.0
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: docker

  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres

  nginx:
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
